// Automatically generated by MockGen. DO NOT EDIT!
// Source: vendor/github.com/cloudfoundry/libbuildpack/command.go

package main_test

import (
	gomock "github.com/golang/mock/gomock"
	io "io"
)

// Mock of Command interface
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *_MockCommandRecorder
}

// Recorder for MockCommand (not exported)
type _MockCommandRecorder struct {
	mock *MockCommand
}

func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &_MockCommandRecorder{mock}
	return mock
}

func (_m *MockCommand) EXPECT() *_MockCommandRecorder {
	return _m.recorder
}

func (_m *MockCommand) SetOutput(_param0 io.Writer) {
	_m.ctrl.Call(_m, "SetOutput", _param0)
}

func (_mr *_MockCommandRecorder) SetOutput(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetOutput", arg0)
}

func (_m *MockCommand) SetStdout(_param0 io.Writer) {
	_m.ctrl.Call(_m, "SetStdout", _param0)
}

func (_mr *_MockCommandRecorder) SetStdout(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetStdout", arg0)
}

func (_m *MockCommand) SetStderr(_param0 io.Writer) {
	_m.ctrl.Call(_m, "SetStderr", _param0)
}

func (_mr *_MockCommandRecorder) SetStderr(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetStderr", arg0)
}

func (_m *MockCommand) Run() error {
	ret := _m.ctrl.Call(_m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCommandRecorder) Run() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Run")
}
